- name: Create Resources Folder
  file:
    path: "{{ docker_folder }}"
    state: directory

- name: Clone
  git:
    repo: "http://{{ username }}:{{ password }}@github.com/kevinaguja/tomcat.git"
    dest: "{{ docker_folder }}"

- name: Download war file
  get_url:
    url: http://54.88.105.117/nexus/content/repositories/snapshots/JavaApplication/CurrencyConverter/1/CurrencyConverter-1.war
    dest: "{{ docker_folder }}/resources"
    mode: 0644
    url_password: "{{ password }}"
    url_username: "{{ username }}"
