---
- name: install pip
  yum: name=python-pip state=latest

- name: work around docker-py
  pip:
    executable=/usr/bin/pip
    name=docker-py
    state=present
    version=1.8.1
    
- name: Delete Container
  docker:
    name: tomcat
    image: "{{ image_version }}"
    state: absent

- name: Build Docker
  docker_image:
    path: "{{ docker_folder }}"
    name: "{{ image_version }}"
    tag: latest
    nocache: yes

- name: Create Container
  docker:
    name: tomcat
    image: "{{ image_version }}"
    state: started
    net: network
    restart_policy: always
    ports: 
    - "{{ ports }}"
    - "54.175.18.225:9999/tcp"
